import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage`. It is gitignored, but eslint does
    // not read .gitignore, so without this a local lint run after a coverage
    // run lints the lcov HTML report's bundled scripts and fails on them.
    "coverage/**",
  ]),
]);

export default eslintConfig;
